#配置数据库信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
#      监控页的配置
      stat-view-servlet:
        enabled: true       #监控页是否开启
        login-username: admin
        login-password: 123456
        reset-enable: false   #重置按钮

#       web监控的功能
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

#        开启功能组件
      filters: stat,wall    #stat:sql监控功能 wall：防火墙监控功能

#      spring监控
      aop-patterns: xf.study.admin.*    #监控这个包下的所有东西

#        对上面filters开启的功能进行详细的配置
      filter:
        stat:
          slow-sql-millis: 1000   #设置超过1000ms的查询就为慢查询
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            update-allow: false


#配置redis相关：
#  redis:
#    host:
#    port:
#    password:
#    client-type:


#配置mybatis规则
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml   #指定mybatis全局配置文件文职
  mapper-locations: classpath:mybatis/mapper/*.xml        #指定mybatis的sql映射文件
  configuration:          #指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true                    #开启驼峰命名(注意：不能跟上面注释的那条全局配置文件的配置一起使用。)



